version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: my-sql
    volumes:
      - ./my-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
    ports:
      - '3306:3306'

volumes:
  db_data: